//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Web_sitemap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Web_sitemap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kwizzotronic.App_LocalResources.Web.sitemap", typeof(Web_sitemap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prekini.
        /// </summary>
        public static string abort {
            get {
                return ResourceManager.GetString("abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte prvi odgovor.
        /// </summary>
        public static string AddAnswer1 {
            get {
                return ResourceManager.GetString("AddAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte drugi odgovor.
        /// </summary>
        public static string AddAnswer2 {
            get {
                return ResourceManager.GetString("AddAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte treći odgovor.
        /// </summary>
        public static string AddAnswer3 {
            get {
                return ResourceManager.GetString("AddAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte četvrti odgovor.
        /// </summary>
        public static string AddAnswer4 {
            get {
                return ResourceManager.GetString("AddAnswer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natrag.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promijeni lozinku.
        /// </summary>
        public static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi novu lozinku.
        /// </summary>
        public static string confirmNewPassword {
            get {
                return ResourceManager.GetString("confirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponovljena lozinka nije ista!.
        /// </summary>
        public static string confirmPasswordDontMatch {
            get {
                return ResourceManager.GetString("confirmPasswordDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Točan odgovor.
        /// </summary>
        public static string correctAnswer {
            get {
                return ResourceManager.GetString("correctAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izradi.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stvori račun.
        /// </summary>
        public static string createAccount {
            get {
                return ResourceManager.GetString("createAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izradite novi korisnički račun.
        /// </summary>
        public static string createNewAccount {
            get {
                return ResourceManager.GetString("createNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj novi kviz.
        /// </summary>
        public static string createNewQuiz {
            get {
                return ResourceManager.GetString("createNewQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj kviz.
        /// </summary>
        public static string createQuiz {
            get {
                return ResourceManager.GetString("createQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završi.
        /// </summary>
        public static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imaš račun?.
        /// </summary>
        public static string doYouHaveAcc {
            get {
                return ResourceManager.GetString("doYouHaveAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi prezime:.
        /// </summary>
        public static string editLastName {
            get {
                return ResourceManager.GetString("editLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi ime:.
        /// </summary>
        public static string editName {
            get {
                return ResourceManager.GetString("editName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi profil.
        /// </summary>
        public static string editProfile {
            get {
                return ResourceManager.GetString("editProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi profil.
        /// </summary>
        public static string editYourProfile {
            get {
                return ResourceManager.GetString("editYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email...
        /// </summary>
        public static string emailHint {
            get {
                return ResourceManager.GetString("emailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesi kod....
        /// </summary>
        public static string enterAccessCode {
            get {
                return ResourceManager.GetString("enterAccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesi nadimak....
        /// </summary>
        public static string enterNickname {
            get {
                return ResourceManager.GetString("enterNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite pitanje....
        /// </summary>
        public static string enterQuestion {
            get {
                return ResourceManager.GetString("enterQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ime kviza....
        /// </summary>
        public static string enterQuizName {
            get {
                return ResourceManager.GetString("enterQuizName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime...
        /// </summary>
        public static string firstNameHint {
            get {
                return ResourceManager.GetString("firstNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netočan odgovor.
        /// </summary>
        public static string incorrectAnswer {
            get {
                return ResourceManager.GetString("incorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netočna stara lozinka!.
        /// </summary>
        public static string incorrectOldPassword {
            get {
                return ResourceManager.GetString("incorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime....
        /// </summary>
        public static string lastNameHint {
            get {
                return ResourceManager.GetString("lastNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaigraj!.
        /// </summary>
        public static string letsPlay {
            get {
                return ResourceManager.GetString("letsPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi se.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moji Kvizovi.
        /// </summary>
        public static string myQuizzes {
            get {
                return ResourceManager.GetString("myQuizzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova lozinka:.
        /// </summary>
        public static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sljedeći.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sljedeće pitanje.
        /// </summary>
        public static string nextQuestion {
            get {
                return ResourceManager.GetString("nextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadimak je zauzet!.
        /// </summary>
        public static string nicknameTaken {
            get {
                return ResourceManager.GetString("nicknameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stara lozinka:.
        /// </summary>
        public static string oldPassword {
            get {
                return ResourceManager.GetString("oldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka....
        /// </summary>
        public static string passwordHint {
            get {
                return ResourceManager.GetString("passwordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igraj.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodovi:.
        /// </summary>
        public static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija:.
        /// </summary>
        public static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prošlo pitanje.
        /// </summary>
        public static string previousQuestion {
            get {
                return ResourceManager.GetString("previousQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pitanje.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rang lista.
        /// </summary>
        public static string rankList {
            get {
                return ResourceManager.GetString("rankList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        public static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreni.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvala na sudjelovanju, .
        /// </summary>
        public static string thanksForParticipating {
            get {
                return ResourceManager.GetString("thanksForParticipating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik već postoji.
        /// </summary>
        public static string userExists {
            get {
                return ResourceManager.GetString("userExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netočan email ili lozinka.
        /// </summary>
        public static string wrongEmailOrPassword {
            get {
                return ResourceManager.GetString("wrongEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemaš račun?.
        /// </summary>
        public static string youDontHaveAcc {
            get {
                return ResourceManager.GetString("youDontHaveAcc", resourceCulture);
            }
        }
    }
}
